name: build and deploy
on: [push, workflow_dispatch]
env:
  NODE_ENV: production
  SECRET: 4
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: print env
        run: |
          echo "${{ env.NODE_ENV }}"
          echo "${{ env.SECRET }}"
      - name: get repo code
        uses: actions/checkout@v3
      - name: install desp
        run: npm install
      - name: run build
        run: npm run build
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: build
          name: build-files
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: build-files
          path: build
