name: deploy react app
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get repo code
        uses: actions/checkout@v3
      - name: cache code
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: install deps
        run: npm install
      - name: run tests
        run: npm run test

  lint:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: get repo code
        uses: actions/checkout@v3
      - name: cache code
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: install deps
        run: npm install
      - name: run lint
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: get repo code
        uses: actions/checkout@v3
      - name: cache code
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: install deps
        run: npm install
      - name: run build
        run: npm run build
      - name: deploy
        run: |
          echo "deploying app"
