name: pull requests
# on: [push, workflow_dispatch]
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: print context
        run: echo "${{ toJSON(github) }}"
